#if CLIENT
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using GameUI;
using GameUI.Brush;
using GameUI.Control;
using GameUI.Control.Advanced;
using GameUI.Control.Primitive;
using GameUI.Control.Struct;
using GameUI.Device;
using GameUI.Enum;
using GameUI.Struct;

namespace GameEntry.GeneratedUi.Spark2.Screens;

public static class ForgeScreen锻造界面
{
    public const string ScreenId = "doc_cf61de2e";

    public static LayoutScreenResult Build(Action<string>? onAction = null)
    {
        var nodes = new Dictionary<string, Control>();
        var root = LayoutEditorSpark2Runtime.Register(nodes, "root", new Panel());
        root.HorizontalAlignment = HorizontalAlignment.Stretch;
        root.VerticalAlignment = VerticalAlignment.Stretch;
        root.Width = 0f;
        root.WidthStretchRatio = 1f;
        root.Height = 0f;
        root.HeightStretchRatio = 1f;
        root.Background = new SolidColorBrush(Color.FromArgb(255, 31, 26, 23));
        var sr_0 = LayoutEditorSpark2Runtime.Register(nodes, "sr_0", new Panel());
        sr_0.Parent = root;
        sr_0.HorizontalAlignment = HorizontalAlignment.Left;
        sr_0.VerticalAlignment = VerticalAlignment.Top;
        sr_0.Width = 1366f;
        sr_0.Height = 768f;
        sr_0.Background = new SolidColorBrush(Color.FromArgb(255, 31, 26, 23));
        var sr_1 = LayoutEditorSpark2Runtime.Register(nodes, "sr_1", new Panel());
        sr_1.Parent = root;
        sr_1.HorizontalAlignment = HorizontalAlignment.Left;
        sr_1.VerticalAlignment = VerticalAlignment.Top;
        sr_1.Width = 1366f;
        sr_1.Height = 56f;
        sr_1.Background = new SolidColorBrush(Color.FromArgb(242, 15, 12, 10));
        var sr_2 = LayoutEditorSpark2Runtime.Register(nodes, "sr_2", new Panel());
        sr_2.Parent = root;
        sr_2.HorizontalAlignment = HorizontalAlignment.Left;
        sr_2.VerticalAlignment = VerticalAlignment.Top;
        sr_2.Width = 1366f;
        sr_2.Height = 2f;
        sr_2.Margin = new Thickness(0f, 54f, 0f, 0f);
        sr_2.Background = new SolidColorBrush(Color.FromArgb(255, 201, 106, 43));
        var plate_3 = LayoutEditorSpark2Runtime.Register(nodes, "plate_3", new Panel());
        plate_3.Parent = root;
        plate_3.HorizontalAlignment = HorizontalAlignment.Left;
        plate_3.VerticalAlignment = VerticalAlignment.Top;
        plate_3.Width = 32f;
        plate_3.Height = 32f;
        plate_3.Margin = new Thickness(20f, 12f, 0f, 0f);
        var plate_bg_4 = LayoutEditorSpark2Runtime.Register(nodes, "plate_bg_4", new Panel());
        plate_bg_4.Parent = plate_3;
        plate_bg_4.HorizontalAlignment = HorizontalAlignment.Left;
        plate_bg_4.VerticalAlignment = VerticalAlignment.Top;
        plate_bg_4.Width = 32f;
        plate_bg_4.Height = 32f;
        plate_bg_4.CornerRadius = 16f;
        var plate_t_5 = LayoutEditorSpark2Runtime.Register(nodes, "plate_t_5", new Label());
        plate_t_5.Parent = plate_3;
        plate_t_5.HorizontalAlignment = HorizontalAlignment.Left;
        plate_t_5.VerticalAlignment = VerticalAlignment.Top;
        plate_t_5.Width = 32f;
        plate_t_5.Height = 32f;
        plate_t_5.Text = "退";
        plate_t_5.FontSize = 14f;
        plate_t_5.TextColor = Color.FromArgb(255, 201, 164, 90);
        plate_t_5.Bold = true;
        plate_t_5.TextWrap = true;
        var tx_6 = LayoutEditorSpark2Runtime.Register(nodes, "tx_6", new Label());
        tx_6.Parent = root;
        tx_6.HorizontalAlignment = HorizontalAlignment.Left;
        tx_6.VerticalAlignment = VerticalAlignment.Top;
        tx_6.Width = 360f;
        tx_6.Height = 24f;
        tx_6.Margin = new Thickness(70f, 16f, 0f, 0f);
        tx_6.Text = "锻造 · 步骤 [3 / 5] 千锤百炼";
        tx_6.FontSize = 18f;
        tx_6.TextColor = Color.FromArgb(255, 201, 164, 90);
        tx_6.Bold = true;
        tx_6.TextWrap = true;
        var stage_7 = LayoutEditorSpark2Runtime.Register(nodes, "stage_7", new Panel());
        stage_7.Parent = root;
        stage_7.HorizontalAlignment = HorizontalAlignment.Left;
        stage_7.VerticalAlignment = VerticalAlignment.Top;
        stage_7.Width = 24f;
        stage_7.Height = 24f;
        stage_7.Margin = new Thickness(1086f, 18f, 0f, 0f);
        stage_7.Background = new SolidColorBrush(Color.FromArgb(255, 79, 122, 99));
        stage_7.CornerRadius = 999f;
        var stage_8 = LayoutEditorSpark2Runtime.Register(nodes, "stage_8", new Panel());
        stage_8.Parent = root;
        stage_8.HorizontalAlignment = HorizontalAlignment.Left;
        stage_8.VerticalAlignment = VerticalAlignment.Top;
        stage_8.Width = 24f;
        stage_8.Height = 24f;
        stage_8.Margin = new Thickness(1122f, 18f, 0f, 0f);
        stage_8.Background = new SolidColorBrush(Color.FromArgb(255, 79, 122, 99));
        stage_8.CornerRadius = 999f;
        var stage_9 = LayoutEditorSpark2Runtime.Register(nodes, "stage_9", new Panel());
        stage_9.Parent = root;
        stage_9.HorizontalAlignment = HorizontalAlignment.Left;
        stage_9.VerticalAlignment = VerticalAlignment.Top;
        stage_9.Width = 24f;
        stage_9.Height = 24f;
        stage_9.Margin = new Thickness(1158f, 18f, 0f, 0f);
        stage_9.Background = new SolidColorBrush(Color.FromArgb(255, 201, 106, 43));
        stage_9.CornerRadius = 999f;
        var stage_a = LayoutEditorSpark2Runtime.Register(nodes, "stage_a", new Panel());
        stage_a.Parent = root;
        stage_a.HorizontalAlignment = HorizontalAlignment.Left;
        stage_a.VerticalAlignment = VerticalAlignment.Top;
        stage_a.Width = 24f;
        stage_a.Height = 24f;
        stage_a.Margin = new Thickness(1194f, 18f, 0f, 0f);
        stage_a.Background = new SolidColorBrush(Color.FromArgb(26, 247, 232, 200));
        stage_a.CornerRadius = 999f;
        var stage_b = LayoutEditorSpark2Runtime.Register(nodes, "stage_b", new Panel());
        stage_b.Parent = root;
        stage_b.HorizontalAlignment = HorizontalAlignment.Left;
        stage_b.VerticalAlignment = VerticalAlignment.Top;
        stage_b.Width = 24f;
        stage_b.Height = 24f;
        stage_b.Margin = new Thickness(1230f, 18f, 0f, 0f);
        stage_b.Background = new SolidColorBrush(Color.FromArgb(26, 247, 232, 200));
        stage_b.CornerRadius = 999f;
        var df_c = LayoutEditorSpark2Runtime.Register(nodes, "df_c", new Panel());
        df_c.Parent = root;
        df_c.HorizontalAlignment = HorizontalAlignment.Left;
        df_c.VerticalAlignment = VerticalAlignment.Top;
        df_c.Width = 1326f;
        df_c.Height = 588f;
        df_c.Margin = new Thickness(20f, 76f, 0f, 0f);
        var sr_d = LayoutEditorSpark2Runtime.Register(nodes, "sr_d", new Panel());
        sr_d.Parent = df_c;
        sr_d.HorizontalAlignment = HorizontalAlignment.Left;
        sr_d.VerticalAlignment = VerticalAlignment.Top;
        sr_d.Width = 1326f;
        sr_d.Height = 588f;
        sr_d.Background = new SolidColorBrush(Color.FromArgb(46, 122, 63, 27));
        sr_d.CornerRadius = 4f;
        var nail_e = LayoutEditorSpark2Runtime.Register(nodes, "nail_e", new Panel());
        nail_e.Parent = df_c;
        nail_e.HorizontalAlignment = HorizontalAlignment.Left;
        nail_e.VerticalAlignment = VerticalAlignment.Top;
        nail_e.Width = 6f;
        nail_e.Height = 6f;
        nail_e.Margin = new Thickness(6f, 6f, 0f, 0f);
        nail_e.Background = new SolidColorBrush(Color.FromArgb(255, 201, 164, 90));
        nail_e.CornerRadius = 999f;
        var nail_f = LayoutEditorSpark2Runtime.Register(nodes, "nail_f", new Panel());
        nail_f.Parent = df_c;
        nail_f.HorizontalAlignment = HorizontalAlignment.Left;
        nail_f.VerticalAlignment = VerticalAlignment.Top;
        nail_f.Width = 6f;
        nail_f.Height = 6f;
        nail_f.Margin = new Thickness(1314f, 6f, 0f, 0f);
        nail_f.Background = new SolidColorBrush(Color.FromArgb(255, 201, 164, 90));
        nail_f.CornerRadius = 999f;
        var nail_g = LayoutEditorSpark2Runtime.Register(nodes, "nail_g", new Panel());
        nail_g.Parent = df_c;
        nail_g.HorizontalAlignment = HorizontalAlignment.Left;
        nail_g.VerticalAlignment = VerticalAlignment.Top;
        nail_g.Width = 6f;
        nail_g.Height = 6f;
        nail_g.Margin = new Thickness(6f, 576f, 0f, 0f);
        nail_g.Background = new SolidColorBrush(Color.FromArgb(255, 201, 164, 90));
        nail_g.CornerRadius = 999f;
        var nail_h = LayoutEditorSpark2Runtime.Register(nodes, "nail_h", new Panel());
        nail_h.Parent = df_c;
        nail_h.HorizontalAlignment = HorizontalAlignment.Left;
        nail_h.VerticalAlignment = VerticalAlignment.Top;
        nail_h.Width = 6f;
        nail_h.Height = 6f;
        nail_h.Margin = new Thickness(1314f, 576f, 0f, 0f);
        nail_h.Background = new SolidColorBrush(Color.FromArgb(255, 201, 164, 90));
        nail_h.CornerRadius = 999f;
        var ph_i = LayoutEditorSpark2Runtime.Register(nodes, "ph_i", new Panel());
        ph_i.Parent = root;
        ph_i.HorizontalAlignment = HorizontalAlignment.Left;
        ph_i.VerticalAlignment = VerticalAlignment.Top;
        ph_i.Width = 1286f;
        ph_i.Height = 548f;
        ph_i.Margin = new Thickness(40f, 96f, 0f, 0f);
        var ph_bg_j = LayoutEditorSpark2Runtime.Register(nodes, "ph_bg_j", new Panel());
        ph_bg_j.Parent = ph_i;
        ph_bg_j.HorizontalAlignment = HorizontalAlignment.Left;
        ph_bg_j.VerticalAlignment = VerticalAlignment.Top;
        ph_bg_j.Width = 1286f;
        ph_bg_j.Height = 548f;
        ph_bg_j.Background = new SolidColorBrush(Color.FromArgb(102, 31, 26, 23));
        ph_bg_j.CornerRadius = 6f;
        var ph_l1_k = LayoutEditorSpark2Runtime.Register(nodes, "ph_l1_k", new Canvas());
        ph_l1_k.Parent = ph_i;
        ph_l1_k.HorizontalAlignment = HorizontalAlignment.Left;
        ph_l1_k.VerticalAlignment = VerticalAlignment.Top;
        ph_l1_k.Width = 1286f;
        ph_l1_k.Height = 548f;
        var ph_l2_l = LayoutEditorSpark2Runtime.Register(nodes, "ph_l2_l", new Canvas());
        ph_l2_l.Parent = ph_i;
        ph_l2_l.HorizontalAlignment = HorizontalAlignment.Left;
        ph_l2_l.VerticalAlignment = VerticalAlignment.Top;
        ph_l2_l.Width = 1286f;
        ph_l2_l.Height = 548f;
        var ph_t_m = LayoutEditorSpark2Runtime.Register(nodes, "ph_t_m", new Label());
        ph_t_m.Parent = ph_i;
        ph_t_m.HorizontalAlignment = HorizontalAlignment.Left;
        ph_t_m.VerticalAlignment = VerticalAlignment.Top;
        ph_t_m.Width = 1286f;
        ph_t_m.Height = 20f;
        ph_t_m.Margin = new Thickness(0f, 264f, 0f, 0f);
        ph_t_m.Text = "【锻造场景占位】熔炉吐焰 + 铁砧 + 锤起锤落动画位\n（运行时由 SpriteAnimation / 火焰特效填充）";
        ph_t_m.FontSize = 14f;
        ph_t_m.TextColor = Color.FromArgb(217, 247, 232, 200);
        ph_t_m.TextWrap = true;
        var df_n = LayoutEditorSpark2Runtime.Register(nodes, "df_n", new Panel());
        df_n.Parent = root;
        df_n.HorizontalAlignment = HorizontalAlignment.Left;
        df_n.VerticalAlignment = VerticalAlignment.Top;
        df_n.Width = 320f;
        df_n.Height = 116f;
        df_n.Margin = new Thickness(36f, 460f, 0f, 0f);
        var sr_o = LayoutEditorSpark2Runtime.Register(nodes, "sr_o", new Panel());
        sr_o.Parent = df_n;
        sr_o.HorizontalAlignment = HorizontalAlignment.Left;
        sr_o.VerticalAlignment = VerticalAlignment.Top;
        sr_o.Width = 320f;
        sr_o.Height = 116f;
        sr_o.Background = new SolidColorBrush(Color.FromArgb(217, 15, 12, 10));
        sr_o.CornerRadius = 4f;
        var nail_p = LayoutEditorSpark2Runtime.Register(nodes, "nail_p", new Panel());
        nail_p.Parent = df_n;
        nail_p.HorizontalAlignment = HorizontalAlignment.Left;
        nail_p.VerticalAlignment = VerticalAlignment.Top;
        nail_p.Width = 6f;
        nail_p.Height = 6f;
        nail_p.Margin = new Thickness(6f, 6f, 0f, 0f);
        nail_p.Background = new SolidColorBrush(Color.FromArgb(255, 201, 164, 90));
        nail_p.CornerRadius = 999f;
        var nail_q = LayoutEditorSpark2Runtime.Register(nodes, "nail_q", new Panel());
        nail_q.Parent = df_n;
        nail_q.HorizontalAlignment = HorizontalAlignment.Left;
        nail_q.VerticalAlignment = VerticalAlignment.Top;
        nail_q.Width = 6f;
        nail_q.Height = 6f;
        nail_q.Margin = new Thickness(308f, 6f, 0f, 0f);
        nail_q.Background = new SolidColorBrush(Color.FromArgb(255, 201, 164, 90));
        nail_q.CornerRadius = 999f;
        var nail_r = LayoutEditorSpark2Runtime.Register(nodes, "nail_r", new Panel());
        nail_r.Parent = df_n;
        nail_r.HorizontalAlignment = HorizontalAlignment.Left;
        nail_r.VerticalAlignment = VerticalAlignment.Top;
        nail_r.Width = 6f;
        nail_r.Height = 6f;
        nail_r.Margin = new Thickness(6f, 104f, 0f, 0f);
        nail_r.Background = new SolidColorBrush(Color.FromArgb(255, 201, 164, 90));
        nail_r.CornerRadius = 999f;
        var nail_s = LayoutEditorSpark2Runtime.Register(nodes, "nail_s", new Panel());
        nail_s.Parent = df_n;
        nail_s.HorizontalAlignment = HorizontalAlignment.Left;
        nail_s.VerticalAlignment = VerticalAlignment.Top;
        nail_s.Width = 6f;
        nail_s.Height = 6f;
        nail_s.Margin = new Thickness(308f, 104f, 0f, 0f);
        nail_s.Background = new SolidColorBrush(Color.FromArgb(255, 201, 164, 90));
        nail_s.CornerRadius = 999f;
        var ph_t = LayoutEditorSpark2Runtime.Register(nodes, "ph_t", new Panel());
        ph_t.Parent = root;
        ph_t.HorizontalAlignment = HorizontalAlignment.Left;
        ph_t.VerticalAlignment = VerticalAlignment.Top;
        ph_t.Width = 92f;
        ph_t.Height = 92f;
        ph_t.Margin = new Thickness(48f, 472f, 0f, 0f);
        var ph_bg_u = LayoutEditorSpark2Runtime.Register(nodes, "ph_bg_u", new Panel());
        ph_bg_u.Parent = ph_t;
        ph_bg_u.HorizontalAlignment = HorizontalAlignment.Left;
        ph_bg_u.VerticalAlignment = VerticalAlignment.Top;
        ph_bg_u.Width = 92f;
        ph_bg_u.Height = 92f;
        ph_bg_u.Background = new SolidColorBrush(Color.FromArgb(46, 201, 164, 90));
        ph_bg_u.CornerRadius = 6f;
        var ph_l1_v = LayoutEditorSpark2Runtime.Register(nodes, "ph_l1_v", new Canvas());
        ph_l1_v.Parent = ph_t;
        ph_l1_v.HorizontalAlignment = HorizontalAlignment.Left;
        ph_l1_v.VerticalAlignment = VerticalAlignment.Top;
        ph_l1_v.Width = 92f;
        ph_l1_v.Height = 92f;
        var ph_l2_w = LayoutEditorSpark2Runtime.Register(nodes, "ph_l2_w", new Canvas());
        ph_l2_w.Parent = ph_t;
        ph_l2_w.HorizontalAlignment = HorizontalAlignment.Left;
        ph_l2_w.VerticalAlignment = VerticalAlignment.Top;
        ph_l2_w.Width = 92f;
        ph_l2_w.Height = 92f;
        var ph_t_x = LayoutEditorSpark2Runtime.Register(nodes, "ph_t_x", new Label());
        ph_t_x.Parent = ph_t;
        ph_t_x.HorizontalAlignment = HorizontalAlignment.Left;
        ph_t_x.VerticalAlignment = VerticalAlignment.Top;
        ph_t_x.Width = 92f;
        ph_t_x.Height = 20f;
        ph_t_x.Margin = new Thickness(0f, 36f, 0f, 0f);
        ph_t_x.Text = "裁\n剪";
        ph_t_x.FontSize = 18f;
        ph_t_x.TextColor = Color.FromArgb(255, 201, 164, 90);
        ph_t_x.TextWrap = true;
        var tx_y = LayoutEditorSpark2Runtime.Register(nodes, "tx_y", new Label());
        tx_y.Parent = root;
        tx_y.HorizontalAlignment = HorizontalAlignment.Left;
        tx_y.VerticalAlignment = VerticalAlignment.Top;
        tx_y.Width = 200f;
        tx_y.Height = 22f;
        tx_y.Margin = new Thickness(150f, 472f, 0f, 0f);
        tx_y.Text = "裁缝绣花剪";
        tx_y.FontSize = 18f;
        tx_y.TextColor = Color.FromArgb(255, 241, 229, 204);
        tx_y.Bold = true;
        tx_y.TextWrap = true;
        var tx_z = LayoutEditorSpark2Runtime.Register(nodes, "tx_z", new Label());
        tx_z.Parent = root;
        tx_z.HorizontalAlignment = HorizontalAlignment.Left;
        tx_z.VerticalAlignment = VerticalAlignment.Top;
        tx_z.Width = 200f;
        tx_z.Height = 16f;
        tx_z.Margin = new Thickness(150f, 496f, 0f, 0f);
        tx_z.Text = "材料 · 寒铁 + 银线钢";
        tx_z.FontSize = 12f;
        tx_z.TextColor = Color.FromArgb(153, 247, 232, 200);
        tx_z.TextWrap = true;
        var tx_10 = LayoutEditorSpark2Runtime.Register(nodes, "tx_10", new Label());
        tx_10.Parent = root;
        tx_10.HorizontalAlignment = HorizontalAlignment.Left;
        tx_10.VerticalAlignment = VerticalAlignment.Top;
        tx_10.Width = 200f;
        tx_10.Height = 16f;
        tx_10.Margin = new Thickness(150f, 514f, 0f, 0f);
        tx_10.Text = "客户期望 · 良品";
        tx_10.FontSize = 12f;
        tx_10.TextColor = Color.FromArgb(255, 79, 122, 99);
        tx_10.TextWrap = true;
        var pg_11 = LayoutEditorSpark2Runtime.Register(nodes, "pg_11", new Panel());
        pg_11.Parent = root;
        pg_11.HorizontalAlignment = HorizontalAlignment.Left;
        pg_11.VerticalAlignment = VerticalAlignment.Top;
        pg_11.Width = 200f;
        pg_11.Height = 18f;
        pg_11.Margin = new Thickness(150f, 538f, 0f, 0f);
        var sr_12 = LayoutEditorSpark2Runtime.Register(nodes, "sr_12", new Panel());
        sr_12.Parent = pg_11;
        sr_12.HorizontalAlignment = HorizontalAlignment.Left;
        sr_12.VerticalAlignment = VerticalAlignment.Top;
        sr_12.Width = 200f;
        sr_12.Height = 18f;
        sr_12.Background = new SolidColorBrush(Color.FromArgb(140, 31, 26, 23));
        sr_12.CornerRadius = 9f;
        var sr_13 = LayoutEditorSpark2Runtime.Register(nodes, "sr_13", new Panel());
        sr_13.Parent = pg_11;
        sr_13.HorizontalAlignment = HorizontalAlignment.Left;
        sr_13.VerticalAlignment = VerticalAlignment.Top;
        sr_13.Width = 121.52f;
        sr_13.Height = 14f;
        sr_13.Margin = new Thickness(2f, 2f, 0f, 0f);
        sr_13.Background = new SolidColorBrush(Color.FromArgb(255, 201, 106, 43));
        sr_13.CornerRadius = 7f;
        var tx_14 = LayoutEditorSpark2Runtime.Register(nodes, "tx_14", new Label());
        tx_14.Parent = pg_11;
        tx_14.HorizontalAlignment = HorizontalAlignment.Left;
        tx_14.VerticalAlignment = VerticalAlignment.Top;
        tx_14.Width = 200f;
        tx_14.Height = 18f;
        tx_14.Text = "完成度 62%";
        tx_14.FontSize = 11f;
        tx_14.TextColor = Color.FromArgb(255, 241, 229, 204);
        tx_14.Bold = true;
        tx_14.TextWrap = true;
        var df_15 = LayoutEditorSpark2Runtime.Register(nodes, "df_15", new Panel());
        df_15.Parent = root;
        df_15.HorizontalAlignment = HorizontalAlignment.Left;
        df_15.VerticalAlignment = VerticalAlignment.Top;
        df_15.Width = 360f;
        df_15.Height = 116f;
        df_15.Margin = new Thickness(986f, 460f, 0f, 0f);
        var sr_16 = LayoutEditorSpark2Runtime.Register(nodes, "sr_16", new Panel());
        sr_16.Parent = df_15;
        sr_16.HorizontalAlignment = HorizontalAlignment.Left;
        sr_16.VerticalAlignment = VerticalAlignment.Top;
        sr_16.Width = 360f;
        sr_16.Height = 116f;
        sr_16.Background = new SolidColorBrush(Color.FromArgb(217, 15, 12, 10));
        sr_16.CornerRadius = 4f;
        var nail_17 = LayoutEditorSpark2Runtime.Register(nodes, "nail_17", new Panel());
        nail_17.Parent = df_15;
        nail_17.HorizontalAlignment = HorizontalAlignment.Left;
        nail_17.VerticalAlignment = VerticalAlignment.Top;
        nail_17.Width = 6f;
        nail_17.Height = 6f;
        nail_17.Margin = new Thickness(6f, 6f, 0f, 0f);
        nail_17.Background = new SolidColorBrush(Color.FromArgb(255, 201, 164, 90));
        nail_17.CornerRadius = 999f;
        var nail_18 = LayoutEditorSpark2Runtime.Register(nodes, "nail_18", new Panel());
        nail_18.Parent = df_15;
        nail_18.HorizontalAlignment = HorizontalAlignment.Left;
        nail_18.VerticalAlignment = VerticalAlignment.Top;
        nail_18.Width = 6f;
        nail_18.Height = 6f;
        nail_18.Margin = new Thickness(348f, 6f, 0f, 0f);
        nail_18.Background = new SolidColorBrush(Color.FromArgb(255, 201, 164, 90));
        nail_18.CornerRadius = 999f;
        var nail_19 = LayoutEditorSpark2Runtime.Register(nodes, "nail_19", new Panel());
        nail_19.Parent = df_15;
        nail_19.HorizontalAlignment = HorizontalAlignment.Left;
        nail_19.VerticalAlignment = VerticalAlignment.Top;
        nail_19.Width = 6f;
        nail_19.Height = 6f;
        nail_19.Margin = new Thickness(6f, 104f, 0f, 0f);
        nail_19.Background = new SolidColorBrush(Color.FromArgb(255, 201, 164, 90));
        nail_19.CornerRadius = 999f;
        var nail_1a = LayoutEditorSpark2Runtime.Register(nodes, "nail_1a", new Panel());
        nail_1a.Parent = df_15;
        nail_1a.HorizontalAlignment = HorizontalAlignment.Left;
        nail_1a.VerticalAlignment = VerticalAlignment.Top;
        nail_1a.Width = 6f;
        nail_1a.Height = 6f;
        nail_1a.Margin = new Thickness(348f, 104f, 0f, 0f);
        nail_1a.Background = new SolidColorBrush(Color.FromArgb(255, 201, 164, 90));
        nail_1a.CornerRadius = 999f;
        var tx_1b = LayoutEditorSpark2Runtime.Register(nodes, "tx_1b", new Label());
        tx_1b.Parent = root;
        tx_1b.HorizontalAlignment = HorizontalAlignment.Left;
        tx_1b.VerticalAlignment = VerticalAlignment.Top;
        tx_1b.Width = 200f;
        tx_1b.Height = 22f;
        tx_1b.Margin = new Thickness(1000f, 472f, 0f, 0f);
        tx_1b.Text = "节拍区  ·  长按蓄力";
        tx_1b.FontSize = 14f;
        tx_1b.TextColor = Color.FromArgb(255, 201, 106, 43);
        tx_1b.Bold = true;
        tx_1b.TextWrap = true;
        var beat_1c = LayoutEditorSpark2Runtime.Register(nodes, "beat_1c", new Panel());
        beat_1c.Parent = root;
        beat_1c.HorizontalAlignment = HorizontalAlignment.Left;
        beat_1c.VerticalAlignment = VerticalAlignment.Top;
        beat_1c.Width = 36f;
        beat_1c.Height = 36f;
        beat_1c.Margin = new Thickness(1000f, 504f, 0f, 0f);
        beat_1c.CornerRadius = 999f;
        var beat_1d = LayoutEditorSpark2Runtime.Register(nodes, "beat_1d", new Panel());
        beat_1d.Parent = root;
        beat_1d.HorizontalAlignment = HorizontalAlignment.Left;
        beat_1d.VerticalAlignment = VerticalAlignment.Top;
        beat_1d.Width = 36f;
        beat_1d.Height = 36f;
        beat_1d.Margin = new Thickness(1050f, 504f, 0f, 0f);
        beat_1d.CornerRadius = 999f;
        var beat_1e = LayoutEditorSpark2Runtime.Register(nodes, "beat_1e", new Panel());
        beat_1e.Parent = root;
        beat_1e.HorizontalAlignment = HorizontalAlignment.Left;
        beat_1e.VerticalAlignment = VerticalAlignment.Top;
        beat_1e.Width = 36f;
        beat_1e.Height = 36f;
        beat_1e.Margin = new Thickness(1100f, 504f, 0f, 0f);
        beat_1e.Background = new SolidColorBrush(Color.FromArgb(255, 201, 164, 90));
        beat_1e.CornerRadius = 999f;
        var beat_1f = LayoutEditorSpark2Runtime.Register(nodes, "beat_1f", new Panel());
        beat_1f.Parent = root;
        beat_1f.HorizontalAlignment = HorizontalAlignment.Left;
        beat_1f.VerticalAlignment = VerticalAlignment.Top;
        beat_1f.Width = 36f;
        beat_1f.Height = 36f;
        beat_1f.Margin = new Thickness(1150f, 504f, 0f, 0f);
        beat_1f.CornerRadius = 999f;
        var beat_1g = LayoutEditorSpark2Runtime.Register(nodes, "beat_1g", new Panel());
        beat_1g.Parent = root;
        beat_1g.HorizontalAlignment = HorizontalAlignment.Left;
        beat_1g.VerticalAlignment = VerticalAlignment.Top;
        beat_1g.Width = 36f;
        beat_1g.Height = 36f;
        beat_1g.Margin = new Thickness(1200f, 504f, 0f, 0f);
        beat_1g.CornerRadius = 999f;
        var plate_1h = LayoutEditorSpark2Runtime.Register(nodes, "plate_1h", new Panel());
        plate_1h.Parent = root;
        plate_1h.HorizontalAlignment = HorizontalAlignment.Left;
        plate_1h.VerticalAlignment = VerticalAlignment.Top;
        plate_1h.Width = 124f;
        plate_1h.Height = 76f;
        plate_1h.Margin = new Thickness(1206f, 484f, 0f, 0f);
        var plate_bg_1i = LayoutEditorSpark2Runtime.Register(nodes, "plate_bg_1i", new Panel());
        plate_bg_1i.Parent = plate_1h;
        plate_bg_1i.HorizontalAlignment = HorizontalAlignment.Left;
        plate_bg_1i.VerticalAlignment = VerticalAlignment.Top;
        plate_bg_1i.Width = 124f;
        plate_bg_1i.Height = 76f;
        plate_bg_1i.Background = new SolidColorBrush(Color.FromArgb(255, 201, 106, 43));
        plate_bg_1i.CornerRadius = 8f;
        var plate_t_1j = LayoutEditorSpark2Runtime.Register(nodes, "plate_t_1j", new Label());
        plate_t_1j.Parent = plate_1h;
        plate_t_1j.HorizontalAlignment = HorizontalAlignment.Left;
        plate_t_1j.VerticalAlignment = VerticalAlignment.Top;
        plate_t_1j.Width = 124f;
        plate_t_1j.Height = 76f;
        plate_t_1j.Text = "锤";
        plate_t_1j.FontSize = 32f;
        plate_t_1j.TextColor = Color.FromArgb(255, 241, 229, 204);
        plate_t_1j.Bold = true;
        plate_t_1j.TextWrap = true;
        var tx_1k = LayoutEditorSpark2Runtime.Register(nodes, "tx_1k", new Label());
        tx_1k.Parent = root;
        tx_1k.HorizontalAlignment = HorizontalAlignment.Left;
        tx_1k.VerticalAlignment = VerticalAlignment.Top;
        tx_1k.Width = 124f;
        tx_1k.Height = 18f;
        tx_1k.Margin = new Thickness(1206f, 540f, 0f, 0f);
        tx_1k.Text = "【按住】";
        tx_1k.FontSize = 11f;
        tx_1k.TextColor = Color.FromArgb(255, 241, 229, 204);
        tx_1k.Bold = true;
        tx_1k.TextWrap = true;
        var sr_1l = LayoutEditorSpark2Runtime.Register(nodes, "sr_1l", new Panel());
        sr_1l.Parent = root;
        sr_1l.HorizontalAlignment = HorizontalAlignment.Left;
        sr_1l.VerticalAlignment = VerticalAlignment.Top;
        sr_1l.Width = 1366f;
        sr_1l.Height = 88f;
        sr_1l.Margin = new Thickness(0f, 680f, 0f, 0f);
        sr_1l.Background = new SolidColorBrush(Color.FromArgb(242, 15, 12, 10));
        var sr_1m = LayoutEditorSpark2Runtime.Register(nodes, "sr_1m", new Panel());
        sr_1m.Parent = root;
        sr_1m.HorizontalAlignment = HorizontalAlignment.Left;
        sr_1m.VerticalAlignment = VerticalAlignment.Top;
        sr_1m.Width = 1366f;
        sr_1m.Height = 2f;
        sr_1m.Margin = new Thickness(0f, 680f, 0f, 0f);
        sr_1m.Background = new SolidColorBrush(Color.FromArgb(255, 201, 164, 90));
        var tx_1n = LayoutEditorSpark2Runtime.Register(nodes, "tx_1n", new Label());
        tx_1n.Parent = root;
        tx_1n.HorizontalAlignment = HorizontalAlignment.Left;
        tx_1n.VerticalAlignment = VerticalAlignment.Top;
        tx_1n.Width = 200f;
        tx_1n.Height = 18f;
        tx_1n.Margin = new Thickness(20f, 686f, 0f, 0f);
        tx_1n.Text = "品质 · 良 → 精";
        tx_1n.FontSize = 14f;
        tx_1n.TextColor = Color.FromArgb(255, 201, 164, 90);
        tx_1n.Bold = true;
        tx_1n.TextWrap = true;
        var pg_1o = LayoutEditorSpark2Runtime.Register(nodes, "pg_1o", new Panel());
        pg_1o.Parent = root;
        pg_1o.HorizontalAlignment = HorizontalAlignment.Left;
        pg_1o.VerticalAlignment = VerticalAlignment.Top;
        pg_1o.Width = 1046f;
        pg_1o.Height = 28f;
        pg_1o.Margin = new Thickness(20f, 708f, 0f, 0f);
        var sr_1p = LayoutEditorSpark2Runtime.Register(nodes, "sr_1p", new Panel());
        sr_1p.Parent = pg_1o;
        sr_1p.HorizontalAlignment = HorizontalAlignment.Left;
        sr_1p.VerticalAlignment = VerticalAlignment.Top;
        sr_1p.Width = 1046f;
        sr_1p.Height = 28f;
        sr_1p.Background = new SolidColorBrush(Color.FromArgb(140, 31, 26, 23));
        sr_1p.CornerRadius = 14f;
        var sr_1q = LayoutEditorSpark2Runtime.Register(nodes, "sr_1q", new Panel());
        sr_1q.Parent = pg_1o;
        sr_1q.HorizontalAlignment = HorizontalAlignment.Left;
        sr_1q.VerticalAlignment = VerticalAlignment.Top;
        sr_1q.Width = 646.04f;
        sr_1q.Height = 24f;
        sr_1q.Margin = new Thickness(2f, 2f, 0f, 0f);
        sr_1q.Background = new SolidColorBrush(Color.FromArgb(255, 201, 106, 43));
        sr_1q.CornerRadius = 12f;
        var tx_1r = LayoutEditorSpark2Runtime.Register(nodes, "tx_1r", new Label());
        tx_1r.Parent = pg_1o;
        tx_1r.HorizontalAlignment = HorizontalAlignment.Left;
        tx_1r.VerticalAlignment = VerticalAlignment.Top;
        tx_1r.Width = 1046f;
        tx_1r.Height = 28f;
        tx_1r.Text = "品质评分 62 / 100  ·  距「精」尚需 88";
        tx_1r.FontSize = 11f;
        tx_1r.TextColor = Color.FromArgb(255, 241, 229, 204);
        tx_1r.Bold = true;
        tx_1r.TextWrap = true;
        var heart_1s = LayoutEditorSpark2Runtime.Register(nodes, "heart_1s", new Canvas());
        heart_1s.Parent = root;
        heart_1s.HorizontalAlignment = HorizontalAlignment.Left;
        heart_1s.VerticalAlignment = VerticalAlignment.Top;
        heart_1s.Width = 32f;
        heart_1s.Height = 28f;
        heart_1s.Margin = new Thickness(1086f, 708f, 0f, 0f);
        var heart_1t = LayoutEditorSpark2Runtime.Register(nodes, "heart_1t", new Canvas());
        heart_1t.Parent = root;
        heart_1t.HorizontalAlignment = HorizontalAlignment.Left;
        heart_1t.VerticalAlignment = VerticalAlignment.Top;
        heart_1t.Width = 32f;
        heart_1t.Height = 28f;
        heart_1t.Margin = new Thickness(1124f, 708f, 0f, 0f);
        var heart_1u = LayoutEditorSpark2Runtime.Register(nodes, "heart_1u", new Canvas());
        heart_1u.Parent = root;
        heart_1u.HorizontalAlignment = HorizontalAlignment.Left;
        heart_1u.VerticalAlignment = VerticalAlignment.Top;
        heart_1u.Width = 32f;
        heart_1u.Height = 28f;
        heart_1u.Margin = new Thickness(1162f, 708f, 0f, 0f);
        var tx_1v = LayoutEditorSpark2Runtime.Register(nodes, "tx_1v", new Label());
        tx_1v.Parent = root;
        tx_1v.HorizontalAlignment = HorizontalAlignment.Left;
        tx_1v.VerticalAlignment = VerticalAlignment.Top;
        tx_1v.Width = 120f;
        tx_1v.Height = 16f;
        tx_1v.Margin = new Thickness(1086f, 738f, 0f, 0f);
        tx_1v.Text = "失误容错 · 2/3";
        tx_1v.FontSize = 11f;
        tx_1v.TextColor = Color.FromArgb(255, 138, 61, 46);
        tx_1v.TextWrap = true;
        var plate_1w = LayoutEditorSpark2Runtime.Register(nodes, "plate_1w", new Panel());
        plate_1w.Parent = root;
        plate_1w.HorizontalAlignment = HorizontalAlignment.Left;
        plate_1w.VerticalAlignment = VerticalAlignment.Top;
        plate_1w.Width = 96f;
        plate_1w.Height = 28f;
        plate_1w.Margin = new Thickness(1246f, 692f, 0f, 0f);
        var plate_bg_1x = LayoutEditorSpark2Runtime.Register(nodes, "plate_bg_1x", new Panel());
        plate_bg_1x.Parent = plate_1w;
        plate_bg_1x.HorizontalAlignment = HorizontalAlignment.Left;
        plate_bg_1x.VerticalAlignment = VerticalAlignment.Top;
        plate_bg_1x.Width = 96f;
        plate_bg_1x.Height = 28f;
        plate_bg_1x.CornerRadius = 14f;
        var plate_t_1y = LayoutEditorSpark2Runtime.Register(nodes, "plate_t_1y", new Label());
        plate_t_1y.Parent = plate_1w;
        plate_t_1y.HorizontalAlignment = HorizontalAlignment.Left;
        plate_t_1y.VerticalAlignment = VerticalAlignment.Top;
        plate_t_1y.Width = 96f;
        plate_t_1y.Height = 28f;
        plate_t_1y.Text = "暂停";
        plate_t_1y.FontSize = 12f;
        plate_t_1y.TextColor = Color.FromArgb(255, 201, 164, 90);
        plate_t_1y.Bold = true;
        plate_t_1y.TextWrap = true;
        var plate_1z = LayoutEditorSpark2Runtime.Register(nodes, "plate_1z", new Panel());
        plate_1z.Parent = root;
        plate_1z.HorizontalAlignment = HorizontalAlignment.Left;
        plate_1z.VerticalAlignment = VerticalAlignment.Top;
        plate_1z.Width = 96f;
        plate_1z.Height = 28f;
        plate_1z.Margin = new Thickness(1246f, 724f, 0f, 0f);
        var plate_bg_20 = LayoutEditorSpark2Runtime.Register(nodes, "plate_bg_20", new Panel());
        plate_bg_20.Parent = plate_1z;
        plate_bg_20.HorizontalAlignment = HorizontalAlignment.Left;
        plate_bg_20.VerticalAlignment = VerticalAlignment.Top;
        plate_bg_20.Width = 96f;
        plate_bg_20.Height = 28f;
        plate_bg_20.CornerRadius = 14f;
        var plate_t_21 = LayoutEditorSpark2Runtime.Register(nodes, "plate_t_21", new Label());
        plate_t_21.Parent = plate_1z;
        plate_t_21.HorizontalAlignment = HorizontalAlignment.Left;
        plate_t_21.VerticalAlignment = VerticalAlignment.Top;
        plate_t_21.Width = 96f;
        plate_t_21.Height = 28f;
        plate_t_21.Text = "道具";
        plate_t_21.FontSize = 12f;
        plate_t_21.TextColor = Color.FromArgb(255, 79, 122, 99);
        plate_t_21.Bold = true;
        plate_t_21.TextWrap = true;
        return new LayoutScreenResult((Panel)root, nodes);
    }

    public static Panel BuildRoot(Action<string>? onAction = null)
    {
        return Build(onAction).Root;
    }

    public static Panel Mount(Action<string>? onAction = null)
    {
        return Build(onAction).Mount();
    }

    public static Panel BuildInto(Control parent, Action<string>? onAction = null)
    {
        var root = BuildRoot(onAction);
        root.Parent = parent;
        return root;
    }

    public static IReadOnlyList<string> ExportNotes()
    {
        return new string[]
        {
            "ShapeRect plate_bg_4 has stroke (width=2, color=#C9A45A). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle stage_7 has stroke (width=2, color=#C9A45A). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle stage_8 has stroke (width=2, color=#C9A45A). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle stage_9 has stroke (width=2, color=#C9A45A). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle stage_a has stroke (width=2, color=#C9A45A). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle stage_b has stroke (width=2, color=#C9A45A). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeRect sr_d has stroke (width=3, color=#C96A2B). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle nail_e has stroke (width=1, color=#3A322B). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle nail_f has stroke (width=1, color=#3A322B). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle nail_g has stroke (width=1, color=#3A322B). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle nail_h has stroke (width=1, color=#3A322B). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeRect ph_bg_j has stroke (width=2, color=rgba(201,106,43,0.5)). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeLine ph_l1_k is exported as Canvas shell. Rebuild draw logic with GameUI.Canvas APIs.",
            "ShapeLine ph_l2_l is exported as Canvas shell. Rebuild draw logic with GameUI.Canvas APIs.",
            "ShapeRect sr_o has stroke (width=2, color=#C9A45A). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle nail_p has stroke (width=1, color=#3A322B). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle nail_q has stroke (width=1, color=#3A322B). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle nail_r has stroke (width=1, color=#3A322B). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle nail_s has stroke (width=1, color=#3A322B). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeRect ph_bg_u has stroke (width=2, color=#C9A45A). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeLine ph_l1_v is exported as Canvas shell. Rebuild draw logic with GameUI.Canvas APIs.",
            "ShapeLine ph_l2_w is exported as Canvas shell. Rebuild draw logic with GameUI.Canvas APIs.",
            "ShapeRect sr_12 has stroke (width=1, color=#C9A45A). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeRect sr_16 has stroke (width=2, color=#C96A2B). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle nail_17 has stroke (width=1, color=#3A322B). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle nail_18 has stroke (width=1, color=#3A322B). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle nail_19 has stroke (width=1, color=#3A322B). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle nail_1a has stroke (width=1, color=#3A322B). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle beat_1c has stroke (width=2, color=#C9A45A). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle beat_1d has stroke (width=2, color=#C9A45A). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle beat_1e has stroke (width=2, color=#C9A45A). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle beat_1f has stroke (width=2, color=#C9A45A). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeCircle beat_1g has stroke (width=2, color=#C9A45A). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeRect plate_bg_1i has stroke (width=3, color=#C9A45A). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeRect sr_1p has stroke (width=1, color=#C9A45A). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapePath heart_1s is exported as Canvas shell. Rebuild draw logic with GameUI.Canvas APIs.",
            "ShapePath heart_1t is exported as Canvas shell. Rebuild draw logic with GameUI.Canvas APIs.",
            "ShapePath heart_1u is exported as Canvas shell. Rebuild draw logic with GameUI.Canvas APIs.",
            "ShapeRect plate_bg_1x has stroke (width=2, color=#C9A45A). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
            "ShapeRect plate_bg_20 has stroke (width=2, color=#4F7A63). Panel does not support BorderBrush. Add a Canvas child or use a separate Panel overlay to draw the stroke.",
        };
    }
}
#endif
